# Generated by Django 4.0.4 on 2022-05-25 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ex', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tip',
            old_name='author',
            new_name='author',
        ),
    ]
